name: app_streaming
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  permission_handler: ^11.4.0
  shared_preferences: ^2.1.1
  http: ^1.4.0
  image_picker: ^0.8.7+4
  flutter_image_compress: ^2.4.0
  intl: any
  zego_uikit_prebuilt_live_streaming: ^3.14.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
